; ---------------------------------------------------------------------------
; fpga.inc
; handy info about locations in the FPGA
; 03-04-19 E. Brombaugh
; ---------------------------------------------------------------------------

.define   GPIO_DATA $D000    ;  GPIO data register location
.define   ACIA_CTRL $E000    ;  ACIA control register location
.define   ACIA_DATA $E001    ;  ACIA data register location

